 

                ===================================
                |                                 |
                |                                 |
                |    Starting Datanator Build     |
                |                                 |
                |                                 |
                ===================================

                

------------------------ Initializing 'build_pax' ------------------------
(psycopg2.IntegrityError) duplicate key value violates unique constraint "physical_entity_pkey"
DETAIL:  Key (observation_id)=(68068) already exists.
 [SQL: 'INSERT INTO physical_entity (type) VALUES (%(type)s)'] [parameters: ({'type': 'Protein Subunit'}, {'type': 'Protein Subunit'}, {'type': 'Protein Subunit'}, {'type': 'Protein Subunit'}, {'type': 'Protein Subunit'}, {'type': 'Protein Subunit'}, {'type': 'Protein Subunit'}, {'type': 'Protein Subunit'}  ... displaying 10 of 4974 total bound parameter sets ...  {'type': 'Protein Subunit'}, {'type': 'Protein Subunit'})] (Background on this error at: http://sqlalche.me/e/gkpj)

------------------------ Initializing 'build_intact_interactions' ------------------------

------------------------ Initializing 'build_sabio' ------------------------

------------------------ Initializing 'build_array_express' ------------------------
(raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (psycopg2.IntegrityError) duplicate key value violates unique constraint "taxon_pkey"
DETAIL:  Key (ncbi_id)=(139) already exists.
 [SQL: 'INSERT INTO taxon (name, search_vector) VALUES (%(name)s, %(search_vector)s) RETURNING taxon.ncbi_id'] [parameters: {'name': None, 'search_vector': None}] (Background on this error at: http://sqlalche.me/e/gkpj)
(raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (psycopg2.IntegrityError) duplicate key value violates unique constraint "taxon_pkey"
DETAIL:  Key (ncbi_id)=(158) already exists.
 [SQL: 'INSERT INTO taxon (name, search_vector) VALUES (%(name)s, %(search_vector)s) RETURNING taxon.ncbi_id'] [parameters: {'name': None, 'search_vector': None}] (Background on this error at: http://sqlalche.me/e/gkpj)
Batch of 5000 interactions was loaded
Batch of 5000 interactions was loaded
Batch of 5000 interactions was loaded
Batch of 5000 interactions was loaded
Batch of 5000 interactions was loaded
Batch of 5000 interactions was loaded
Batch of 5000 interactions was loaded
Batch of 5000 interactions was loaded
Batch of 5000 interactions was loaded
Batch of 5000 interactions was loaded
Batch of 5000 interactions was loaded
Batch of 5000 interactions was loaded
Batch of 5000 interactions was loaded
Batch of 5000 interactions was loaded
Batch of 5000 interactions was loaded
Comitting
'build_intact_interactions' took 10103.89 sec
'build_intact_interactions' completed

------------------------ Initializing 'build_uniprot' ------------------------
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.IntegrityError) duplicate key value violates unique constraint "physical_entity_pkey"
DETAIL:  Key (observation_id)=(68068) already exists.
 [SQL: 'INSERT INTO physical_entity (type) VALUES (%(type)s)'] [parameters: ({'type': 'Protein Subunit'}, {'type': 'Protein Subunit'}, {'type': 'Protein Subunit'}, {'type': 'Protein Subunit'}, {'type': 'Protein Subunit'}, {'type': 'Protein Subunit'}, {'type': 'Protein Subunit'}, {'type': 'Protein Subunit'}  ... displaying 10 of 4974 total bound parameter sets ...  {'type': 'Protein Subunit'}, {'type': 'Protein Subunit'})] (Background on this error at: http://sqlalche.me/e/gkpj)

------------------------ Initializing 'build_ncbi' ------------------------
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.IntegrityError) duplicate key value violates unique constraint "physical_entity_pkey"
DETAIL:  Key (observation_id)=(68068) already exists.
 [SQL: 'INSERT INTO physical_entity (type) VALUES (%(type)s)'] [parameters: ({'type': 'Protein Subunit'}, {'type': 'Protein Subunit'}, {'type': 'Protein Subunit'}, {'type': 'Protein Subunit'}, {'type': 'Protein Subunit'}, {'type': 'Protein Subunit'}, {'type': 'Protein Subunit'}, {'type': 'Protein Subunit'}  ... displaying 10 of 4974 total bound parameter sets ...  {'type': 'Protein Subunit'}, {'type': 'Protein Subunit'})] (Background on this error at: http://sqlalche.me/e/gkpj)
 

                =============================================
                |                                           |
                |             Finished Build                |
                    Total time taken for build: 10107.48 secs
                |                                           |
                =============================================
                
